# Site settings
title: A Journey Through Becoming a Developer
header-img: img/home-bg.png
email: michael.james.randell@gmail.com
copyright_name: MIKE-RANDELL
description: > # this means to ignore newlines until "baseurl:"
  my thoughts on the path of learning and becoming a Web Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MIKE-RANDELL
learn_profile: MIKE-RANDELL
email_username: michael.james.randell@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
